version: "3.7"

services:
  mongodb:
    image: mongo:4.2
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db/
    networks:
      - fatodo

volumes:
  db:

networks:
  fatodo:
    external:
      name: fatodo
