{
 "title": "Fatodo JWM",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "[[tag_service]]",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "process_uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "[[tag_service]]",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "2xx requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "[[tag_routeUri]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "routeUri" ], "type": "tag" }
     ],
     "measurement": "spring_cloud_gateway_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "OK" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "CREATED" }
     ]
    }
   ]
  },
  {
   "title": "3xx, 4xx and 5xx requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "[[tag_routeUri]] - [[tag_httpStatusCode]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "routeUri" ], "type": "tag" },
      { "params": [ "httpStatusCode" ], "type": "tag" }
     ],
     "measurement": "spring_cloud_gateway_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "!=", "value": "OK" },
      { "condition": "AND", "key": "status", "operator": "!=", "value": "CREATED" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage by service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "[[tag_service]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM total memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_service]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap' AND \"service\" = 'auth-service') AND $timeFilter GROUP BY time($__interval), \"id\" fill(null)",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "JVM heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_service]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap' AND \"service\" = 'auth-service') AND $timeFilter GROUP BY time($__interval), \"id\" fill(null)",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "area", "operator": "=", "value": "heap" }
     ]
    }
   ]
  },
  {
   "title": "JVM nonheap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_service]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service" ], "type": "tag" }
     ],
     "measurement": "jvm_memory_used",
     "region": "default",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "statistics": [ "Average" ],
     "tags": [
      { "key": "area", "operator": "=", "value": "nonheap" }
     ]
    }
   ]
  }
 ]
}