version: "3.7"

services:

  config-server:
    image: fatodo-config-server
    restart: always
    ports:
      - "8888:8888"
    networks:
      - fatodo
    volumes:
      - ../../fatodo-config-repo/:/tmp/fatodo-config-repo/
    environment:
      SPRING_PROFILES_DEFAULT: docker
      WAIT_HOSTS: mongodb:27017, mysql:3306, redis:6379, rabbitmq:5672

  registry:
    image: fatodo-registry
    restart: always
    ports:
      - "8761:8761"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_DEFAULT: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: config-server:8888

  gateway:
    image: fatodo-gateway
    restart: always
    ports:
      - "4000:4000"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  auth-service:
    image: fatodo-auth-service
    restart: always
    ports:
      - "8001:8001"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  user-service:
    image: fatodo-user-service
    restart: always
    ports:
      - "8002:8002"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  item-service:
    image: fatodo-item-service
    restart: always
    ports:
      - "8003:8003"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  mail-service:
    image: fatodo-mail-service
    restart: always
    ports:
      - "8005:8005"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  image-service:
    image: fatodo-image-service
    restart: always
    ports:
      - "8006:8006"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  contact-service:
    image: fatodo-contact-service
    restart: always
    ports:
      - "8007:8007"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  chat-service:
    image: fatodo-chat-service
    restart: always
    ports:
      - "8008:8008"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  ws-service:
    image: fatodo-ws-service
    restart: always
    ports:
      - "8009:8009"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  comment-service:
    image: fatodo-comment-service
    restart: always
    ports:
      - "8010:8010"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  notification-service:
    image: fatodo-notification-service
    restart: always
    ports:
      - "8011:8011"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

  event-service:
    image: fatodo-event-service
    restart: always
    ports:
      - "8012:8012"
    networks:
      - fatodo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_HOST: config-server
      WAIT_HOSTS: registry:8761

networks:
  fatodo:
    name: fatodo
