version: "3.7"

services:
  mongodb:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - fatodo
    volumes:
      - mongodb:/data/db/

volumes:
  mongodb:

networks:
  fatodo:
    external:
      name: fatodo
