version: "3.7"

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fatodo
    volumes:
      - redis:/data/
    command: redis-server --requirepass dev

volumes:
  redis:

networks:
  fatodo:
    external:
      name: fatodo
