version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.10.7-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "61613:61613"
    networks:
      - fatodo
    volumes:
      - ./config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbitmq:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq-user
      RABBITMQ_DEFAULT_PASS: dev

volumes:
  rabbitmq:

networks:
  fatodo:
    name: fatodo
